### ISSUE TITLE
Dark Mode / Light Mode in new online Swift Book

### ISSUE THREAD

**Issue by alebmp** [apple/swift-book#119]
**Description**

I would like to point out that in the new format of the Swift Book (on Swift.org), a footer has been inserted which does not allow the dark mode/light mode switch to be seen and used. The mode therefore depends solely on the general setting of the Mac. In my case, this is definitely inconvenient because I can only use Dark Mode which (at least for me) is very annoying.

I don't know if this is the right place for this report, and if not, I apologise.

**Steps to reproduce**

**Expected behavior**

**Environment**
- Swift compiler version info 
- Xcode version info 
- Deployment target:

**Comment by krilnon** [comment]
Thanks for the ping; somehow I missed Ben's earlier. This is fixed by #110 for this book, and I filed a broader issue for DocC-Render here: https://github.com/apple/swift-docc-render/issues/546.

**Comment by griffrawk** [comment]
Could I make a request for dark mode to be not-so-dark mode? Or at least an option of an in-between like the Rust book has? The current dark mode contrast is a bit too stark, so the the white lettering is also a bit too strong.

**Comment by amartini51** [comment]
@griffrawk Can you [open an issue](https://github.com/apple/swift-docc/issues/new/choose) against DocC about that please?  It's good feedback, but TSPL doesn't define its own style sheet.  It just uses the colors that come from DocC.
