### ISSUE TITLE
Incorrect text in the unownedOptionalReference diagram

### ISSUE THREAD

**Issue by nhowell** [apple/swift-book#135]
### Location

The page in the docs where it appears:
https://docs.swift.org/swift-book/documentation/the-swift-programming-language/automaticreferencecounting#Unowned-Optional-References

The actual files in the repository:
https://github.com/apple/swift-book/blob/main/TSPL.docc/Assets/unownedOptionalReference@2x.png
https://github.com/apple/swift-book/blob/main/TSPL.docc/Assets/unownedOptionalReference~dark@2x.png

### Description

The 3rd course is named "p" in the diagram, which doesn't match the example code above it.

### Correction

The 3rd course should be named "Caring for Tropical Plants".

rdar://109160486

**Comment by amartini51** [comment]
Thanks for filing this issues!

I've sent a request to one of our designers to edit this figure and make the correction.
