### ISSUE TITLE
Update "headings" section of style guide

### ISSUE THREAD

**Issue by benrimmington** [apple/swift-book#15]
The book's [style guide][] lists the underlines for ReStructured Text headings.
However, the book uses `#`-prefixed [ATX headings][].

[ATX headings]: <https://github.github.com/gfm/#atx-headings>
[style guide]: <https://github.com/apple/swift-book/blob/main/Style.md#headings>

**Comment by krilnon** [comment]
Good catch; it might even make sense to remove the syntax descriptions and leave the advice about nesting headings, since people are probably already familiar with the `#`-style headings.

**Comment by amartini51** [comment]
Thanks.  In the PR's rewrite, I kept one sentence of markup guidance, just to avoid any ambiguity, since CommonMark does support underlined headings.
