### ISSUE TITLE
Incorrect content in 4CC macro example

### ISSUE THREAD

**Issue by grynspan** [apple/swift-book#170]
### Location

https://github.com/apple/swift-book/blob/main/TSPL.docc/LanguageGuide/Macros.md?plain=1#L543

### Description

This macro should use `UInt32(bigEndian:)` to convert _from_ big-endian to native-endian rather than converting _to_ big-endian.

### Correction

```diff
- return result.bigEndian
+ return UInt32(bigEndian: result)
```

**Comment by grynspan** [comment]
Wait… no…

The way we naturally express bitwise math in English (and in Swift) is big-endian. That is, the `<<` and `>>` operators shift bits up and down respectively, and `9,876,543` is ordered with the highest digit (`9`) in the highest position, which is the first position, i.e. big-end-first.

This operation:

```swift
for character in characters {
    result = result << 8
    guard let asciiValue = character.asciiValue else { return nil }
    result += UInt32(asciiValue)
}
```

Always shifts result **up**, i.e. toward the big end, by 8 bits. This is correct without regard to the internal representation of a number. So the correct solution is to not use `.bigEndian` or `UInt32(bigEndian:)`, and to just return result as-is. The caller can then byte-swap if they need explicit big- or little-endian ordering for whateve reason.

**Comment by amartini51** [comment]
Having spent some time working through this, I'm pretty sure the correct behavior would be to return a native-endian 32-bit integer.  The caller can write `someFourCC.bigEndian` when they need the actual big-endian value, like they do with other integers.

The linked branch has part of that change — right now, the macro still returns an plain integer literal, whose type is assumed to be `Int`, and could be 32- or 64-bit.
