### ISSUE TITLE
Grammar of "infix expression" does not allow `await`

### ISSUE THREAD

**Issue by jansorg** [apple/swift-book#179]
### Location

https://docs.swift.org/swift-book/documentation/the-swift-programming-language/summaryofthegrammar/#Expressions
in section "Grammar of an infix expression"

### Description

AFAIK this is valid ([user's bug report](https://github.com/jansorg/swift-plugin/issues/24) for the JetBrains Swift plugin):
```
var device: Device?
device = try await viewModel.getDevice(id: id)
```

and if I'm not mistaken this part of the grammar is missing the `await` support:

```
infix-expression → infix-operator prefix-expression
infix-expression → assignment-operator try-operator? prefix-expression
infix-expression → conditional-operator try-operator? prefix-expression
infix-expression → type-casting-operator
infix-expressions → infix-expression infix-expressions?
```

### Correction

Add the `await` as it's supported by this?
```
# Grammar of an expression
expression → try-operator? await-operator? prefix-expression infix-expressions?
expression-list → expression | expression , expression-list
```

**Comment by amartini51** [comment]
I think the change you're asking for is to add `await` to the grammar for prefix expressions?

The grammar already looks like what's in the Correction section above:

https://github.com/apple/swift-book/blob/main/TSPL.docc/ReferenceManual/Expressions.md?plain=1#L23

> Grammar of an expression:
>
> *expression* → *try-operator*_?_ *await-operator*_?_ *prefix-expression* *infix-expressions*_?_ \
> *expression-list* → *expression* | *expression* **`,`** *expression-list*

Looking at the example in the linked issue:

```
device = try await viewModel.getDevice(id: id)
```

And walking through the grammar production:

- expression `device = try await viewModel.getDevice(id: id)`
  - prefix expression `device`
  - infix expression `= try await viewModel.getDevice(id: id)`
    - assignment operator operator `=`
    - try operator `try`
    - No grammar to generate `await` here
    - prefix-expression `try await viewModel.getDevice(id: id)`
        - (…)

**Comment by jansorg** [comment]
Oh, sorry, my note in the section „Correction“ was misleading. I meant to support the await keyword for „infix-expression“ in the same way it‘s already supported by the grammar of „expression“. Your suggested change looks correct to me and is what I had in mind.

**Comment by amartini51** [comment]
@jansorg Thanks for the confirmation.  I opened a PR to review and incorporate this fix.
