### ISSUE TITLE
Unreachable production in Swift grammar

### ISSUE THREAD

**Issue by sarahnicoleboo** [apple/swift-book#187]
### Location

https://docs.swift.org/swift-book/documentation/the-swift-programming-language/summaryofthegrammar/

### Description

Under "Grammar of a declaration" there is a production:
declarations -> declaration declarations?

There exists no path to reach this production.
That is to say, there are no other productions where declarations appears on the right hand side, nor is declarations the top-level entry point for the grammar.

Therefore, this production is unreachable.

### Correction

This production should be removed from the grammar.

**Comment by amartini51** [comment]
The old definition of 'enum-body' used 'declarations' — it looks like this was left behind during a refactoring.

https://github.com/apple/swift-book/blob/main/TSPL.docc/ReferenceManual/Declarations.md?plain=1#L1816

```
enum-declaration -> attribute-list-OPT ``enum`` enum-name generic-parameter-clause-OPT type-inheritance-clause-OPT enum-body
enum-name -> identifier
enum-body -> ``{`` declarations-OPT ``}``
```
