### ISSUE TITLE
Version Compatibility page Swift book has incorrect information about version required for concurrency

### ISSUE THREAD

**Issue by rtharston** [apple/swift-book#21]
## Describe the bug

The second to last paragraph of the Version Compatibility page of the Swift book incorrectly states concurrency requires '5.7 or later'. It should state '5.5 or later'. (My guess is someone did a 'replace all'.)

The same paragraph also says to, "set a deployment target of at least iOS 15, macOS 12, tvOS 15, or watchOS 8.0" which was correct at the time Swift 5.5 was released, but since Xcode 13.2 it is possible to use Swift Concurrency (but not all the new APIs) back to ["macOS Catalina 10.15, iOS 13, tvOS 13, and watchOS 6"](https://developer.apple.com/documentation/xcode-release-notes/xcode-13_2-release-notes).

## To Reproduce

1. Go to [Version Compatibility](https://docs.swift.org/swift-book/GuidedTour/Compatibility.html)
2. Scroll down to second to last paragraph
3. See error

## Expected behavior

State facts.

## Actual behavior

State mix of old facts and new find-and-replace error.

## Screenshots

<img width="750" alt="image" src="https://user-images.githubusercontent.com/12513211/172491563-2e95e112-b922-4dd1-a29d-b828c5d92485.png">

## Environment details

N/A

### Swift.org version/commit hash

Swift 5.7 book (that is all I could find)

## Additional context 

N/A

**Comment by amartini51** [comment]
Transferred to the TSPL repo and re-opened.
