### ISSUE TITLE
Reference or grammar should include a full list of keywords & context-sensitive keywords

### ISSUE THREAD

**Issue by sarahnicoleboo** [apple/swift-book#211]
### Location

https://github.com/apple/swift-book/blob/main/TSPL.docc/ReferenceManual/SummaryOfTheGrammar.md?plain=1#L1021

### Description

1) Include somewhere in the documentation a complete list of keywords in Swift, what they do, and where they can be acceptably used. There currently exists some description of keywords in the Lexical Structure doc but it is incomplete and convoluted due to the fact that it's focusing on which keywords can be used as identifiers outside of their specific context.

2) Ideally the grammar production for balanced-token should be self-sufficient and not require someone to search through the documentation to find what things such as a keyword, literal, or punctuation are. The productions should ideally be written in the correct format rather than including prose. This wouldn't be too much of a problem if 1) was fixed.

### Motivation

The motivation for this issue occurred when I was trying to determine what is a syntactically acceptable balanced-token in Swift.
The grammar production for balanced token uses English prose as seen below:
balanced-token → ( balanced-tokens? )
balanced-token → [ balanced-tokens? ]
balanced-token → { balanced-tokens? }
balanced-token → Any identifier, keyword, literal, or operator
balanced-token → Any punctuation except (, ), [, ], {, or }

From this, it is not very clear what is syntactically acceptable for a balanced-token.
identifier, literal, and operator have productions in the grammar which can be looked up within the same file.
keyword and punctuation do not appear anywhere in the grammar.
As stated above, they are covered in the Lexical Structure doc.
That doc gives a complete definition for punctuation.
It does not give a complete definition for keywords.

This is an issue that is larger than what is syntactically acceptable for a balanced-token as this is a small use case.
Ideally a programming language's documentation should include an unabridged definition for the keywords in the language.
This addition would be helpful for beginner and advanced programmers alike who are using the language.

**Comment by amartini51** [comment]
@sarahnicoleboo Do you think this is largely the same issue as https://github.com/apple/swift-book/issues/101 ?  If we had a full list of keywords in the reference, that seems like it would resolve most of this issue.

We're unlikely to formalize the grammar for attributes much beyond where they are now, because the parser for each attribute is different.  (At least, they were when I wrote that grammar.)  So the details of what can go in the `( )` is basically anything that the attribute's implementation in the compiler understands, but with some general restrictions that it has to be "balanced" so the lexer can read it and make an AST.

**Comment by sarahnicoleboo** [comment]
@amartini51 Yes! Having a full list of keywords would resolve most of the issue. Looks like this is indeed expressed in issue #101
Feel free to close this issue if you wish since the fix is already being tracked.

**Comment by amartini51** [comment]
Thanks, @sarahnicoleboo — we'll track this issue there.
