### ISSUE TITLE
Prose refers to NonsendableTemperatureReading, which isn't in the code listing

### ISSUE THREAD

**Issue by mucki-at** [apple/swift-book#224]
### Location

https://docs.swift.org/swift-book/documentation/the-swift-programming-language/concurrency

### Description

The final paragraph reads:

"In the code above, the NonsendableTemperatureReading is a structure that meets the criteria to be implicitly sendable. However, the extension makes its conformance to Sendable unavailable, preventing the type from being sendable."

However the code above has no such structures and is about a different sample. 

### Correction

Unclear. Either the paragraph is a  leftover from a previous version and should be removed, or rewritten to apply to the actual sample code (FileDescriptor)

**Comment by amartini51** [comment]
Looks like a leftover from c554b62bcc3162a4df2fd61ffc41634e16c6b733 which changed the code listing. Thanks for calling this out!

**Comment by mucki-at** [comment]
No problem at all.
