### ISSUE TITLE
Language Provision Referenced in A Swift Tour not Given in Language Guide

### ISSUE THREAD

**Issue by tadbyt** [apple/swift-book#232]
### Location

https://docs.swift.org/swift-book/documentation/the-swift-programming-language/collectiontypes

### Description

In the 7th paragraph of the Simple Values subsection of _A Swift Tour_, the final sentence reads:  A comma is allowed after the last element.  Unlike other language provisions of Swift contained in _A Swift Tour_, it was not repeated in the corresponding detailed subsections in the _Language Guide_ or _Language Reference_.  It should be.

### Correction

In the _Creating an Array with an Array Literal_ subsection, add the sentence "A comma is allowed after the last element"  as a standalone paragraph following the first example.  Alternatively, modify the first example to have a comma after the final element and append the sentence to the end of the preceding paragraph.

No change is required in the _Creating a Set with an Array Literal_ subsection as the description of an array literal is not repeated there, merely that it may be used.

In the _Creating a Dictionary with a Dictionary Literal_ subsection, add the sentence "A comma is allowed after the last element" as a standalone paragraph following the first example.  Alternatively, modify the first example to have a comma after the final element and append the sentence to the end of the preceding paragraph.

**Comment by tadbyt** [comment]
While it is not given in the _Language Guide_, it does appear in the _Language Reference_.

**Comment by amartini51** [comment]
Thanks for checking.  I think this is ok as is too.  The "trailing comma" form works well when each item is on its own line, but the examples in the guide don't use that syntax.
