### ISSUE TITLE
Update the Concurrency Section Subtitle

### ISSUE THREAD

**Issue by tadbyt** [apple/swift-book#238]
### Location

https://docs.swift.org/swift-book/documentation/the-swift-programming-language/concurrency

### Description

The current chapter abstract is "Perform asynchronous operations."

### Correction

The abstract should be "Perform asynchronous and parallel operations."

**Comment by amartini51** [comment]
Most of the emphasis of Swift concurrency is on async, not parallelism — it may need some discussion about whether to change that emphasis.

**Comment by tadbyt** [comment]
Fair enough.
