### ISSUE TITLE
Missing Code Sample in Sendable Types

### ISSUE THREAD

**Issue by tadbyt** [apple/swift-book#239]
### Location

https://docs.swift.org/swift-book/documentation/the-swift-programming-language/concurrency#Sendable-Types

### Description

The final paragraph in the subsection reads:   In the code above, the NonsendableTemperatureReading is a structure that meets the criteria to be implicitly sendable. However, the extension makes its conformance to Sendable unavailable, preventing the type from being sendable.

The problem is that there is no code sample that contains the NonsendableTemperatureReading structure.

### Correction

Find the missing code sample and incorporate it above the final paragraph.  It's also not in the 5.7 version of TSPL, so I'm not sure what it is.

**Comment by amartini51** [comment]
This is fixed in commit 7b40a139ebd6e95278c2d05dddc6c3b305d9eecc which will be merged by PR #228.
