### ISSUE TITLE
Update for Type and Value Parameter Packs [SE-0393]

### ISSUE THREAD

**Issue by tadbyt** [apple/swift-book#246]
### Location

https://docs.swift.org/swift-book/documentation/the-swift-programming-language/generics 
https://docs.swift.org/swift-book/documentation/the-swift-programming-language/types 
https://docs.swift.org/swift-book/documentation/the-swift-programming-language/expressions 
https://docs.swift.org/swift-book/documentation/the-swift-programming-language/declarations#Function-Declaration 
https://docs.swift.org/swift-book/documentation/the-swift-programming-language/genericparametersandarguments 
https://docs.swift.org/swift-book/documentation/the-swift-programming-language/summaryofthegrammar#Types 
https://docs.swift.org/swift-book/documentation/the-swift-programming-language/summaryofthegrammar/#Expressions 
https://docs.swift.org/swift-book/documentation/the-swift-programming-language/summaryofthegrammar/#Declarations 
https://docs.swift.org/swift-book/documentation/the-swift-programming-language/summaryofthegrammar#Generic-Parameters-and-Arguments 

https://github.com/apple/swift-evolution/blob/main/proposals/0393-parameter-packs.md#proposed-solution 
https://github.com/apple/swift-evolution/blob/main/proposals/0393-parameter-packs.md#detailed-design 
https://www.swift.org/blog/swift-5.9-released/ 

### Description

1)	Two alternative approaches are proposed, depending on whether the bulk of the content is more suited for the _Language Guide_ (option A) or the _Language Reference_ (option B).  In both options, the bulk of the material was extracted from the _Proposed Solution_ and _Detailed Design_ subsections of SE-0393.  The material was revised slightly to change the orientation from that of a proposal to being embedded in _The Swift Programming Language_, to move the set of key concepts to follow the first example, and to enable the first example to compile and yield the designated results.
a.	Option A
i.	Create a new _Type and Value Parameter Packs_ section (see first attachment) at the end of the _Language Guide_ section.
ii.	Create a new _Pack Expansion Type_ subsection (see second attachment) at the end of the _Types_ section.  The _Grammar for pack expansion type_ (see fifth attachment) would conclude this new subsection.
b.	Option B
i.	Append a new _Type and Value Parameter Packs_ subsection to the _Generics_ subsection (see third attachment).
ii.	Create a new _Type and Value Parameter Packs_ section (see fourth attachment) immediately preceding the _Summary of the Grammar_ section that is an extracted rewording of the _Detailed Design_ subsection of SE-0393.  _The Grammar for pack expansion type_ (see fifth attachment) would conclude this new section.
2)	Update the various affected grammars in both the initial subsection in which they appear and in the _Summary of the Grammar_ (see fifth attachment).
3)	Update the discussion in the affected feature subsections, placing a link to the corresponding discussion in the new section (see six attachment).
4)	Add **each** to _Keywords reserved in particular contexts_ in the _Keywords and Punctuation_ subsection. 

Note:  The known open issues identified with this proposal are:
1)	One who was involved with SE-0393 should review the final sentence in the _Constrained Protocol Types_ paragraph, replicated unchanged from SE-0393.  It refers to “Cases 2, 3, 4 or 5 above” where there doesn’t appear to be five cases, only three.
2)	The term “brace statement” is used in the first sentence of the last paragraph of the _Syntactic validity_ subsection of the _Value parameter packs_ subsection.  Should this be “code block” instead?
3)	Not all examples, replicated unchanged from SE-0393, compile.  Compiler warnings indicate that it aware of parameter pack involvement, but the code copied and pasted from the document as is doesn’t compile as-is.  One who was involved with the writing of SE-0393 should review and adjust the examples as required.
4)	Changes to the grammar for SE-0393 are non-trivial (see fifth attachment).  They were backed out of the discussion and examples in the _Detailed Design_ subsection of SE-0393 and should be reviewed for accuracy, completeness, and style consistent with rest of the grammar by one of those involved with its implementation or working on the compiler.  The grammar fragments are given in their expected order in the _Summary of the Grammar_ section.
5)	Changes to the grammar (see fifth attachment) drive the corresponding textual changes to the _Language Reference_ (see sixth attachment).  Once the grammar changes have been reviewed, the corresponding textual revisions should be updated to match.
6)	A few additional examples should be provided to cover each of the major points described.

Should either option be seriously considered, then permission should be obtained from and credit given to SE-0393’s authors, Holly Borla, John McCall and Slava Pestov.

Should there be interest in documenting Type and Value Parameter Packs and permission not be forthcoming from SE-0393’s authors, then consider the following stop-gap measure:

1)	Evaluate and incorporate the requisite grammar changes (see 2 above).
2)	Incorporate the corresponding text changes (see 1 a. ii. and 3 above) putting the links directly to the appropriate points in SE-0393.
3)	Append a stub _Type and Value Parameter Packs_ section with the fragment discussing _Parameter Packs_ extracted from the Swift 5.9 is Release blog entry (again, with permission) retaining the link to SE-0393.

[Type and Value Parameter Packs Option A Language Guide section.pdf](https://github.com/apple/swift-book/files/13933780/Type.and.Value.Parameter.Packs.Option.A.Language.Guide.section.pdf)
[Type and Value Parameter Packs Option A Language Reference subsection.pdf](https://github.com/apple/swift-book/files/13933782/Type.and.Value.Parameter.Packs.Option.A.Language.Reference.subsection.pdf)
[Type and Value Parameter Packs Option B Language Guide subsection.pdf](https://github.com/apple/swift-book/files/13933783/Type.and.Value.Parameter.Packs.Option.B.Language.Guide.subsection.pdf)
[Type and Value Parameter Packs Option B Language Reference section.pdf](https://github.com/apple/swift-book/files/13933800/Type.and.Value.Parameter.Packs.Option.B.Language.Reference.section.pdf)
[Type and Value Parameter Packs Affected Grammars.pdf](https://github.com/apple/swift-book/files/13933802/Type.and.Value.Parameter.Packs.Affected.Grammars.pdf)
[Type and Value Parameter Packs Affected Language Reference Text.pdf](https://github.com/apple/swift-book/files/13933804/Type.and.Value.Parameter.Packs.Affected.Language.Reference.Text.pdf)

### Motivation

Type and Value Parameter Packs [SE-0393] is a headline language feature implemented in Swift 5.9, affects the language syntax and semantics, and is not currently documented in either the _Language Guide_ or _Language Reference_.  This proposal was developed to incorporate this feature into _The Swift Programming Language_ as rapidly as possible while being as faithful to SE-0393 as possible as well as minimize impacts to the existing grammar and text.

### Alternatives Considered

1)	Revise the proposed solution by transferring the new _Type and Value Parameter Packs_ section to be a subsection of the _Types_ section.
a.	Rejected as this subsection would then dominate the whole _Types_ section and would be inconsistent in tone, level of detail, and orientation of the other subsections.
2)	Revise the proposed solution Option B by omitting the new _Type and Value Parameter Packs_ subsection in the Generics section.  The Option A counterpart is to the Option B _Type and Value Parameter Packs_ section in the Language Guide.
a.	Rejected as that new subsection serves as a good introduction to the concepts, whether as a subsection in the Generics section or as the introduction to the new section.
3)	Revise the proposed solution Option B by basing the new _Type and Value Parameter Packs_ subsection in the _Generics_ section on the Swift 5.9 is Released discussion of _Parameter Packs_.  The Option A counterpart is to use this as the introduction.
a.	Rejected as that fragment may be too succinct and potentially misinterpreted.
4)	Writing a new subsection in lieu of the reworded SE-0393 _Proposed Solution_ subsection from scratch.
a.	Rejected as SE-0393 has been reviewed multiple times and this would further delay documenting the feature.
5)	Writing a new section in lieu of the reworded SE-0393 _Detailed Design_ from scratch.
a.	Rejected as SE-0393 has been reviewed multiple times and this would further delay documenting the feature.  Also, there is a lot of technical detail provided and some of this could be inadvertently lost or altered.
6)	Revise the proposed solution by not creating the new subsection and section, but rather providing a reference in the _Language Reference_ back to SE-0393.  This would retain both the changes to the grammar and the brief textual updated in the _Language Reference_ subsections.
a.	Rejected as this approach hasn’t been used elsewhere in the book.  Further, the tone of SE-0393 is expectant that its inclusion may foster further changes that would alter the behavior from what was adopted.  Having extracted out the relevant content into the book will make it easier to change that in the book should this occur.

**Comment by tadbyt** [comment]
The attached indicates the initial set of changes that are necessary to convert the markdown of SE-0393 to a Language Guide section.  Purple indicates merely content to be added or deleted.  Red indicates content to be moved.  These changes do not resolve the open issues.

[Parameter Packs.pdf](https://github.com/apple/swift-book/files/13942635/Parameter.Packs.pdf)

**Comment by amartini51** [comment]
You are correct that copying the SE proposal into TSPL isn't a suitable way to document a language feature.

The changes for parameter packs were pitched in [this forum thread](https://forums.swift.org/t/tspl-pitch-macros-and-parameter-packs/64339) and the branch with a rich outline is here:

https://github.com/apple/swift-book/compare/main...amartini51:swift-book:pack_102835487

You're welcome to start expanding parts of that outline.
