### ISSUE TITLE
missing word in Concurrency:Actors section

### ISSUE THREAD

**Issue by hayne** [apple/swift-book#247]
### Location

https://docs.swift.org/swift-book/documentation/the-swift-programming-language/concurrency

### Description

There seems to be a word missing in the following sentence:

"The convertFarenheitToCelsius() method above is method, ..."

**Comment by amartini51** [comment]
Thanks!  This was fixed by PR #222 and merged to 'main', and the fixed version will go out with the next version of TSPL.
