### ISSUE TITLE
missing example code in Concurrency:Sendable section

### ISSUE THREAD

**Issue by hayne** [apple/swift-book#248]
### Location

https://docs.swift.org/swift-book/documentation/the-swift-programming-language/concurrency

### Description

At the end of the Sendable section, the following sentence appears:

"In the code above, the NonsendableTemperatureReading is a structure that meets the criteria to be implicitly sendable."

But there is no such code above.

**Comment by amartini51** [comment]
Thanks!  This was fixed by PR #228 and merged into 'main', and will be corrected in the next update of TSPL.
