### ISSUE TITLE
Unused Expression-List Term / Production in Grammar

### ISSUE THREAD

**Issue by tadbyt** [apple/swift-book#274]
### Location

https://docs.swift.org/swift-book/documentation/the-swift-programming-language/summaryofthegrammar#Expressions

### Description

The _expression-list_ term is only referenced in its own production.  Either this is an unnecessary production, perhaps obsolete, or another production that should reference it is missing or incorrect.

### Correction

If _expression-list_ is no longer used, remove its production.

If it should be used, correct the production that should reference it.

**Comment by amartini51** [comment]
This used to be used by the array grammar, before it was revised in 27491635d9cda7e71208643f16b758302a5016c7.

This likely is no longer needed.
