### ISSUE TITLE
Improve the presentation of grammar elements

### ISSUE THREAD

**Issue by krilnon** [apple/swift-book#3]
Right now, the grammar in Language Reference is implemented using plain code listings. The shipping book includes a custom presentation for the grammar, including cross-references between different grammar elements and a page that hosts the generated summary of the grammar. 

rdar://101001280

**Comment by amartini51** [comment]
Filed https://github.com/apple/swift-book/issues/48 to track navigation separately as a "parity" issue.

One approach we could take using the markup currently available in DocC is to use note boxes.

- Use a note title like "Grammar of an expression"
- Write definition a new paragraph, so it appears on its own line
- Use a Unicode arrow to separate the two sides of the rule
- Use code voice for literal tokens (bold code voice isn't available)
- Use a suffix "?" to mark optionality
- Use plain (aka roman) font for English descriptions of rules

**Comment by amartini51** [comment]
Correction: DocC _does_ support bold code voice, which I think makes using italic ? to mark optionality visually distinctive enough.  There aren't any grammar productions that include an optional `?` token, so we wouldn't have **`?`** followed by _?_ anywhere currently.

![image](https://user-images.githubusercontent.com/15617351/195461042-14d7f09b-41c6-4dd9-90f2-fc6c663b86eb.png)

**Comment by amartini51** [comment]
I've pitched this approach for grammar [on the Swift forums](https://forums.swift.org/t/60848).
