### ISSUE TITLE
List of keywords is missing `borrowing` and `consuming`

### ISSUE THREAD

**Issue by amartini51** [apple/swift-book#300]
### Location

https://docs.swift.org/swift-book/documentation/the-swift-programming-language/lexicalstructure/#Keywords-and-Punctuation

### Description

It looks like the [PR](https://github.com/apple/swift-book/pull/173) that added reference for them didn't update the lists of keywords.

(As discussed this forum thread: https://forums.swift.org/t/71488)

**Comment by twof** [comment]
The list of keywords is also missing `distributed`
