### ISSUE TITLE
Name the ~= (pattern matching?) operator when introducing it

### ISSUE THREAD

**Issue by swift-ci** [apple/swift-book#304]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-896      |
   |Radar             | None         |
   |Original Reporter | douglashill (JIRA User)      |
   |Type              | Improvement    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 1         |
   |Component/s       | Standard Library    |
   |Labels            | Improvement, Documentation        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: fccac19dc8668e07b859568b36ae3644

  </details>

**Issue Description:**

Reading through the Swift book in iBooks, the \~= is mentioned but not named. There are numerous advantages to having a clear name:

-   We can vocalise internally while reading and writing code. Many of us need to think using language: it is how we structure our thoughts.

-   We can vocalise while speaking (rather than writing) to other people about Swift.

-   Provides guidance on expected behaviours when overloading the operator.

-   Names are easier to search for. Most search engines (including Google and Jira) seem to ignore \~=.

I am sorry if I am missing the name somewhere; it's hard to search for.

https://docs.swift.org/swift-book/documentation/the-swift-programming-language/patterns

**Comment by Azoy** [comment]
@AnthonyLatsis done

**Comment by amartini51** [comment]
Calling it the "pattern-matching operator" seems reasonable to me.

**Comment by amartini51** [comment]
Confirmed with Brian (who wrote the original version of this circa 2014) — there doesn't seem to be any reason to avoid naming this operator.
