### ISSUE TITLE
Broken anchor tag on colliding "#main"

### ISSUE THREAD

**Issue by thatrobotdev** [apple/swift-book#309]
### Location

https://docs.swift.org/swift-book/documentation/the-swift-programming-language/attributes/#main

### Description

The anchor tag for the "main" section under ["Declaration Attributes"](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/attributes/#Declaration-Attributes) does not take you to the correct section, breaking both the anchor URL https://docs.swift.org/swift-book/documentation/the-swift-programming-language/attributes/#main and the right side navigation bar.

I think this is because the h3#main shares the same id with the main element with id #main.

### Correction

The anchor tag should be fixed not to collide with the other "#main" id.

**Comment by amartini51** [comment]
This is a known issue with DocC: https://github.com/apple/swift-docc-render/issues/788
