### ISSUE TITLE
Document default types for associated values

### ISSUE THREAD

**Issue by natecook1000** [apple/swift-book#40]
We don't appear to document the way you can provide a default type in an associate's type declaration. Noted in https://forums.swift.org/t/a-question-about-associatedtype-in-protocols/16168

The [grammar of a protocol associated type declaration](https://docs.swift.org/swift-book/ReferenceManual/Declarations.html#grammar_protocol-associated-type-declaration) includes an optional _typealias-assignment_ clause, but doesn't explain what the meaning of that is. An explanation could probably be added to the [Associated Types](https://docs.swift.org/swift-book/LanguageGuide/Generics.html#ID189) section of the Generics article.

This was originally tracked by https://github.com/apple/swift-book/issues/41.

**Comment by amartini51** [comment]
I've transferred the original issue (https://github.com/apple/swift-book/issues/41) so we can close this duplicate.
