### ISSUE TITLE
Operator Declarations link

### ISSUE THREAD

**Issue by endeavour42** [apple/swift-book#57]
### Location

https://docs.swift.org/swift-book/LanguageGuide/AdvancedOperators.html

### Description

https://docs.swift.org/swift-book/LanguageGuide/AdvancedOperators.html has this:

> For information about the operators provided by the Swift standard library, including a complete list of the operator precedence groups and associativity settings, see [Operator Declarations](https://developer.apple.com/documentation/swift/operator_declarations).

links to apple page. I believe it should be linked to a page hosted on docs.swift.org.

**Comment by amartini51** [comment]
What page do you think it should link to instead?  There's no documentation on docs.swift.org for the Swift standard library.

**Comment by endeavour42** [comment]
A new page with contents matching https://developer.apple.com/documentation/swift/operator-declarations

**Comment by endeavour42** [comment]
Is this a standard library matter? E.g. to know that `a + b * c` means `a + (b * c)` and not `(a + b) * c`

**Comment by amartini51** [comment]
I don't think a request to write new documentation for the Swift standard library, or to migrate the existing content is in scope here, since this repository is for "The Swift Programming Language".  I'll mark this as an enhancement for now, and revisit.

**Comment by endeavour42** [comment]
Perhaps half of the stuff in there belongs to the language itself? How possible to have, say, "is" / "as" operators defined in standard library? or "=", or a ternary operator, probably a good half of the list.

**Comment by amartini51** [comment]
Closing as not applicable to "The Swift Programming Language" because these operators aren't part of the language, and because the standard library operators are documented along with the rest of the standard library.
