### ISSUE TITLE
Improve the chapter navigation experience

### ISSUE THREAD

**Issue by krilnon** [apple/swift-book#6]
The book's chapters are divided into three parts: the Guided Tour, Language Guide, and Language Reference. As a result, the automatically generated See Also sections at the end of each chapter are fairly distracting (and obviated somewhat by DocC's new sidebar). We should consider adopting [some proposed DocC improvements](https://forums.swift.org/t/supporting-more-types-of-documentation-with-swift-docc/59725#automaticseealso-14) like `@AutomaticSeeAlso(disabled)` and `@AutomaticPagination`.

rdar://101885438

**Comment by amartini51** [comment]
As of https://github.com/apple/swift-docc/pull/368 we can now disable the automatic see-also and customize the "eyebrow" title.  Automatic pagination looks like that's still future DocC work.

**Comment by amartini51** [comment]
https://github.com/amartini51/swift-book/tree/navigation_6
