### ISSUE TITLE
optional protocols being limited to classes that inherit from Object-C classes: compiler check?

### ISSUE THREAD

**Issue by ByunghoonKim** [apple/swift-book#66]
**Describe the bug**

Hi, I am currently learning Swift programming language.
[Optional Protocol Requirements](https://docs.swift.org/swift-book/LanguageGuide/Protocols.html#ID284l) section in the official Swift programming language document(Swift 5.7) states

> Note that @objc protocols can be adopted only by classes that inherit from Objective-C classes or other @objc classes. They can’t be adopted by structures or enumerations.

and provides an example code.
```
@objc protocol CounterDataSource {
    @objc optional func increment(forCount count: Int) -> Int
    @objc optional var fixedIncrement: Int { get }
}

// ...

class ThreeSource: NSObject, CounterDataSource {
    let fixedIncrement = 3
}
```

Xcode, however, readily accepts the following code snippet which does *not* inherit NSObject, and compiles without any problem.
```
class ThreeSource: /*NSObject,*/ CounterDataSource {
    let fixedIncrement = 3
}
```

Then, am I to understand that the document's description on the limitation is about why optional protocol is introduced to the language in the first place, and not about what is actually enforced by the compiler?

**Screenshots**
<img width="1142" alt="Screenshot 2022-11-03 at 17 50 45" src="https://user-images.githubusercontent.com/44054076/199681061-752da893-9a72-428e-bcbd-9c2c7b641b1f.png">

**Environment (please fill out the following information)**
 - OS: [macOS 13.0]
 - Xcode Version/Tag/Branch: Xcode Version 14.1 (14B47b)

**Comment by amartini51** [comment]
I think the issue is that the wording here can be read two ways:

> Note that `@objc` protocols can be adopted only by classes that inherit from Objective-C classes, or adopted by classes that inherit from other `@objc` classes.

Or, possibly:

> Note that `@objc` protocols can be adopted only by classes that inherit from Objective-C classes, or adopted by other `@objc` classes.

I believe the first one is correct, and is what was intended when this was written in 2015 (commit 084c87c).  This matches the example above: the `ThreeSource` class inherits from `CounterDataSource`, and the `CounterDataSource` class is an `@objc` class.

**Comment by slavapestov** [comment]
The following code works:

```swift
import Foundation

@objc protocol P {}
class C: P {}
```

C is not @objc, and we do not infer the @objc attribute on it. So I think the correct wording is

> Note that `@objc` protocols can only be adopted by classes. They can't be adopted by structures or enumerations.
