### ISSUE TITLE
Fix building documentation warnings

### ISSUE THREAD

**Issue by Kyle-Ye** [apple/swift-book#9]
1. Warning as error
Currently, there are 63 warnings when we try to build the documentation.

I think we should fix them and consider adding the --warning-as-error flag to the PR's CI workflow when the such ability is implemented. 
https://forums.swift.org/t/add-support-for-warnings-as-errors/59832/5

2. Fake warnings
But it turns out the current 63 warnings are mostly useless warnings and should be fixed in swift-docc side.

- 2.1 Maybe we should just ignore all the contents in `@Comment`?(about 2/3 of warnings are caused by this) cc @franklinsch 
- 2.2 There is a warning saying "Link in document summary will not be displayed" but it is actually displayed.
<img width="959" alt="image" src="https://user-images.githubusercontent.com/43724855/187506365-719302e3-4765-4e55-96fe-82f8abc45507.png">
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/43724855/187506461-2bd98441-2549-4183-b166-bccac2b20c18.png">

> Env: Xcode 14.0 beta 6 with its bundled default Swift toolchain

**Comment by amartini51** [comment]
The warning in the first screenshot about a link in an abstract will be fixed by #1 (add chapter abstracts).

**Comment by Kyle-Ye** [comment]
Update:
Issue 1 was fixed by the recent updated in swift-docc. And we can enable such feature by passing `--warnings-as-errors` to swift-docc
Issue 2-1 is tracked by https://github.com/apple/swift-docc/issues/377
Issue 2-2 is tracked by #1

**Comment by amartini51** [comment]
Thanks, @Kyle-Ye.  Since everything described here is being tracked elsewhere, I'll close this issue.

**Comment by Kyle-Ye** [comment]
> Update:
> Issue 1 was fixed by the recent updated in swift-docc via [apple/swift-docc#365](https://github.com/apple/swift-docc/pull/365). And we can enable such feature by passing `--warnings-as-errors` to swift-docc
> Issue 2-1 is tracked by [apple/swift-docc#377](https://github.com/apple/swift-docc/issues/377)
> Issue 2-2 is tracked by #1

Update:
Issue 3: Actually misused links
eg.
swift-book try to reference `#### Switching Over Future Enumeration Cases` in Statements.md but it looks like swift-docc only support `###` at most

Should we reopen this issue to track it or should we add a new issue here or on swift-docc?🤔
